#!/usr/bin/env bash
# set -u
set -eo pipefail

# ========== Tootils ==========
#
# Tootils works as a dispatcher of *Operations* ($op), which are handled
# by their respective modules and visually presented to the user
# surrounded by text that displays the external command ran.
# This is handled by runOP() and runOpBatch().
#
# Functions starting with a capital letter are the entry point
# of the module with the same name.
#
# Function signature is expressed as the first group of lines
# at the top of the function.
#

declare op=$1
shift

#shellcheck disable=SC2034
declare -A conf
declare SYSTEM HERE config_dir config_file config_file_backup

# ===== Essential functions =====

erro() {
    echo "$C_RED!$C_RESET${*}" >&2
    return 1
}

fatal() {
    echo "$C_RED!$C_RESET${*}" >&2
    exit 1
}

fatal-assert() {
    erro " - Fatal Assertion Failure (bug):"
    fatal "$*"
}

#shellcheck disable=SC1090
load-module() {
    local mod="$HERE/tootils_modules/tt_$1.sh"

    source "$mod" 2>/dev/null || fatal "Could not load module: $mod"
}

canonical-path() {
    local path=$1

    local old_path
    while true; do
        old_path=$path
        path=$(readlink -e -- "$path")
        (( $? )) && return 1
        [[ $path == "$old_path" ]] && break
    done

    echo "$path"
}

# ========== Main body ==========

# Tootils path
HERE=$(canonical-path "$0")
HERE=${HERE%/*} # dirname

# Include <stdlib.h>
load-module "lib"

# System recognition
if command -v cygpath &>/dev/null; then
    SYSTEM=win
else
    SYSTEM=lin
fi

# Configuration logic
if [[ -z $XDG_CONFIG_HOME ]]; then
    XDG_CONFIG_HOME="$HOME/.config"
elif [[ $SYSTEM == 'win' ]]; then
    XDG_CONFIG_HOME=$(cygpath -u "$XDG_CONFIG_HOME")
fi

config_dir="$XDG_CONFIG_HOME/tootils"
config_file="$config_dir/tootils.conf"
config_file_backup="$config_dir/backup.conf"

# this could be improved as it looks the dirtiest of all hehe
# oh, I know, I'll make a `tootils.conf.template` and copy its data
if [[ ! -f $config_file ]]; then
    mkdir -p "$config_dir"
    touch "$config_file"
    (( $? )) && fatal "Could not create configuration file at location: $config_file"

    echo -e "# Tootils fresh config\n# Comment lines start with #\n# Fill the following required entries:\n\nbackup_root=\n" > "$config_file"

    echo "Configuration file created at location: $config_file"
    echo "Please set it up with your desired values and relaunch Tootils."
    exit 0
fi
# hastily written. might be fine though
if [[ ! -f $config_file_backup ]]; then
    touch "$config_file_backup"
    (( $? )) && fatal "Could not create configuration file at location: $config_file_backup"
fi

load-config "conf" "backup_root" "" < "$config_file"

# Print the title
echo " ${C_RED_B_BL}-Tootils-${C_RESET}"

# Main
case "$op" in
    bk|bkg|back|backg)
        load-module "backup"
        Backup "$op" "$@"
        ;;
    help)
        load-module "help"
        Help "$@"
        ;;
    "")
        # to be improved
        # this should and will print usage information instead of crying
        echo "usage:"
        echo "    'toot <subcommand> [arg]'"
        echo "usage and help under construction. yeesh!"
        ;;
    *)
        erro "Unknown Tootils command: $op"
        ;;
esac
